### ISSUE TITLE
SSO/Client Cert

### ISSUE THREAD

**Issue by kylecribbs** [mwa21/rsa_archer#3]
Are you accepting merge requests? I would like to add in SSO Credentials and Client Cert to this library.

**Comment by kylecribbs** [comment]
bump?

**Comment by ghost** [comment]
Hi, sorry about the late response (

Sure, let's try ) I promise I'll appear here more often )

**Comment by Gee19** [comment]
I added SSL cert validation in my fork here:
https://github.com/Gee19/rsa_archer

I've fixed a bunch of flake8 lint issues and formatted with [black](https://github.com/psf/black)

EDIT: I just saw https://github.com/kylecribbs/pyarcher/

Will have to check it out.

**Comment by kylecribbs** [comment]
Yeah no disrespect but the code was sub-par and I decided to hard fork.

**Comment by ghost** [comment]
No worries, I weeded to write the code ASAP. Planned to refactor it, but as usual, there are more important tasks.
Thanks for the link!

**Comment by kylecribbs** [comment]
I appreciate the positive response. I started writing the pyarcher to google docstyle standards and using CI/CD if you want to contribute? I still have a lot to do and that would help
